# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/ide_extension/intellij/"
    target-branch: "next"
    schedule:
      interval: "weekly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/ide_extension/intellij/"
    target-branch: "next"
    schedule:
      interval: "weekly"
  # Maintain dependencies for pip dependencies
  - package-ecosystem: "pip"
    directory: "/tools/"
    target-branch: "next"
    schedule:
      interval: "daily"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/docker/"
    target-branch: "next"
    schedule:
      interval: "weekly"
