steps:

- task: UsePythonVersion@0
  displayName: 'Use Python'
  inputs:
    versionSpec: '>= 3.6'
  enabled: false

- task: UsePythonVersion@0
  displayName: 'Use Python'
  inputs:
    versionSpec: '>= 3.6'
  enabled: false

- script: |
    python3 -m pip install --upgrade pip -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
    python3 -m pip install setuptools virtualenv wheel -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
    python3 -m virtualenv _venv
    source _venv/bin/activate
    python -m pip install -r requirements.txt -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
    echo "[distutils]" >> .pypirc
    echo "index-servers = local" >> .pypirc
    echo "[local]" >> .pypirc
    if [ "$(Build.SourceBranch)" == "refs/heads/trunk" ]; then
      echo "repository:$(url_repository_artifactory_pdn)" >> .pypirc
      echo "username: $(Artifactory.user)" >> .pypirc
      echo "password: $(Artifactory.Password)" >> .pypirc
      cp .pypirc $HOME
      python3 setup.py bdist_wheel upload -r local
      python3 setup.py sdist upload -r local
    else
      python -m build
      curl -u$(Artifactory.user):$(Artifactory.Password) -T $(System.DefaultWorkingDirectory)/$(componentName)/$(TARGET_FILE_PATH) "https://artifactory.apps.bancolombia.com/artifactory/devops-toolset/$(System.DefaultWorkingDirectory)/$(componentName)/$(TARGET_FILE_PATH)"
    fi
  workingDirectory: $(System.DefaultWorkingDirectory)/$(componentName)
  displayName: 'Artifact creation and upload'
  
- task: SonarQubePrepare@4
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: SonarQube
    scannerMode: CLI
    configMode: manual
    cliProjectKey: '$(repositoryName)'
    cliProjectName: '$(repositoryName)'
    cliProjectVersion: '$(Build.BuildNumber)'
    extraProperties: |
      sonar.verbose=true
      sonar.sources=$(System.DefaultWorkingDirectory)/$(componentName)
      sonar.python.coverage.reportPaths =$(System.DefaultWorkingDirectory)/$(componentName)/coverage.xml
      sonar.language=py
      sonar.exclusion=**/devsecops_engine_utilities/**,**/applications/**,**/pipelines/**,**/test/**,**/example/**,**setup.py**,**hello_world**,**Dockerfile**,**/coverage/**,**/azure-pipelines.yml/**
      sonar.coverage.exclusions=**/devsecops_engine_utilities/**,**/applications/**,**/pipelines/**,**/test/**,**/example/**,**setup.py**,**hello_world**,**Dockerfile/**,**/coverage/**,**/azure-pipelines.yml/**
- script:  |
    python3 -m pip install --upgrade pip -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
    python3 -m pip install setuptools virtualenv wheel -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
  displayName: install python basics

- script: |
    python3 -m virtualenv _venv
    source _venv/bin/activate
    python -m pip install --upgrade pip -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
    python -m pip install -r requirements.txt -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com
    python -m pytest -x --cov=$(System.DefaultWorkingDirectory)/$(componentName) --cov-config=.coveragerc
    python -m coverage report -m
    python -m coverage xml
  workingDirectory: $(System.DefaultWorkingDirectory)/$(componentName)
  displayName: 'Run Unit Test'


- task: PublishTestResults@2
  displayName: 'Publish Test Results **/out*.xml'
  inputs:
    testResultsFiles: '**/out*.xml'
    searchFolder: $(System.DefaultWorkingDirectory)/$(componentName)


- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: coverage.xml
    pathToSources: $(System.DefaultWorkingDirectory)/$(componentName)
  continueOnError: false

- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'

- task: sonar-buildbreaker@8
  displayName: 'Break build on quality gate failure'
  inputs:
    SonarQube: SonarQube
