
trigger:
- trunk

pool:
  name: Release-cloud

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo "##vso[task.setvariable variable=RELEASE_VERSION]$(Build.SourceBranchName#refs/heads/v)"
  displayName: 'Set lib version'

- task: InstallPython@0
  inputs:
    versions: 'python;pythonx86'
    versionlist: '3.12'

- task: PythonScript@0
  inputs:
    scriptSource: 'get_files_gh.py'
    arguments: '$(repo-owner) $(project) rules $(gh-at) rules'

- task: PythonScript@0
  inputs:
    scriptSource: 'get_files_ad.py'
    arguments: '$(repo-owner-ad) $(project-ad) engine_core $(ad-at) actual_remote_config'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'docker/Dockerfile'
    tags: 'bancolombia/devsecops-engine-tools:$(VERSION)'
    arguments: 'VERSION=$(VERSION) REMOTE_CONFIG_PATH=$(REMOTE_CONFIG_PATH)'

- task: ArtifactoryDocker@1
  displayName: Docker Push
  inputs:
    command: 'push'
    repository: 'devops/devsecops-engine-tools'
    artifactoryService: 'Artifactory'
    targetRepo: 'devops/devsecops-engine-tools'
    imageName: 'artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(version)'