
trigger:
- trunk

pool:
  name: Azure Pipelines

steps:

- task: connect-agent@2
  displayName: 'Hosted agent'
  inputs:
    hostedAgentService: 90469226-70c7-4fd9-acf1-a6f54739e00a

- script: echo "##vso[task.setvariable variable=RELEASE_VERSION]$(Build.SourceBranchName#refs/heads/v)"
  displayName: 'Set lib version'

- script: pwd && ls
  displayName: 'Test'

- script: python3 docker/get_files_ad.py $(repo-owner-ad) $(project-ad) engine_core $(ad-at) actual_remote_config
  displayName: 'Get Custom Remote Config'

- script: python3 docker/get_files_gh.py $(repo-owner) $(project) rules $(gh-at) rules
  displayName: 'Get Custom IAC Rules'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'docker/Dockerfile'
    tags: 'bancolombia/devsecops-engine-tools:$(VERSION)'
    arguments: '--build-arg VERSION=$(VERSION) --build-arg REMOTE_CONFIG_PATH=$(REMOTE_CONFIG_PATH)'

- task: ArtifactoryDocker@1
  displayName: Docker Push
  inputs:
    command: 'push'
    repository: 'devops/devsecops-engine-tools'
    artifactoryService: 'Artifactory'
    targetRepo: 'devops/devsecops-engine-tools'
    imageName: 'artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(version)'