
trigger:
- trunk

pool:
  name: Azure Pipelines

steps:

- task: connect-agent@2
  displayName: 'Hosted agent'
  inputs:
    hostedAgentService: 90469226-70c7-4fd9-acf1-a6f54739e00a

- script: |
    version=$(python3 -c "import sys; sys.path.append('tools/devsecops_engine_tools'); import version; print(version.version)")
    echo "##vso[task.setvariable variable=RELEASE_VERSION]$version"
  displayName: 'Set lib version from version.py'

- script: echo "Release version is $(RELEASE_VERSION)"
  displayName: 'Use the release version'

- script: python3 docker/get_files_ad.py $(repo-owner-ad) "$(project-ad)" NU0429001_DevSecOps_Remote_Config /engine_sast/engine_iac/ConfigTool.json $(ad-at) path
  displayName: 'Get Custom Remote Config'

- script: python3 docker/get_files_gh.py $(repo-owner) $(project) rules $(gh-at) rules
  displayName: 'Get Custom IAC Rules'

- script: docker build --build-arg VERSION=$(RELEASE_VERSION) -t artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(RELEASE_VERSION) -f docker/Dockerfile . && docker tag artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(RELEASE_VERSION) artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(RELEASE_VERSION)
  displayName: 'Build Docker Image'

- task: ArtifactoryDocker@1
  displayName: Docker Push
  inputs:
    command: 'push'
    repository: 'devops/devsecops-engine-tools'
    artifactoryService: 'Artifactory'
    targetRepo: 'devops/devsecops-engine-tools'
    imageName: 'artifactory.apps.bancolombia.com/devops/devsecops-engine-tools:$(RELEASE_VERSION)'