name: Manual Docker Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'DevSecOps Engine Tools Version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  manual-docker-release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make git

      - name: Clone specific version of KICS
        run: |
          git clone https://github.com/Checkmarx/kics.git /tmp/kics
          cd /tmp/kics
          git checkout tags/$KICS_VERSION
        env:
          KICS_VERSION: ${{ vars.KICS_VERSION }}

      - name: Run go mod vendor
        working-directory: /tmp/kics
        run: go mod vendor
        
      - name: Build KICS binary
        working-directory: /tmp/kics
        run: |
          mkdir -p bin
          go build -o ./bin/kics cmd/console/main.go

      - name: Validate KICS
        run: |
          if [ ! -f /tmp/kics/bin/kics ]; then
            echo "Error: KICS binary was not generated"
            exit 1
          fi
          file /tmp/kics/bin/kics
          chmod +x /tmp/kics/bin/kics
          /tmp/kics/bin/kics version || echo "Error: KICS compiled, but does not run correctly"

      - name: Move KICS binary to custom folder
        run: |
          mkdir -p ./kics_binary/kics-devsecops
          cp /tmp/kics/bin/kics ./kics_binary/kics-devsecops/
          ls -la ./kics_binary
          ls -la ./kics_binary/kics-devsecops
          
      - name: Build and tag Docker image
        timeout-minutes: 3
        run: |
          docker build --build-arg VERSION=${{ github.event.inputs.version }} -t bancolombia/devsecops-engine-tools:${{ github.event.inputs.version }} -f docker/Dockerfile .
          docker tag bancolombia/devsecops-engine-tools:${{ github.event.inputs.version }} bancolombia/devsecops-engine-tools:${{ github.event.inputs.version }}

      - name: devsecops-engine-tools engine_container
        run: |
          set -e
          # Install devsecops-engine-tools
          pip3 install devsecops-engine-tools -q

          # Execute devsecops-engine-tools and handle the output
          output=$(devsecops-engine-tools --platform_devops github --remote_config_source local --remote_config_repo example_remote_config_local --module engine_container --tool trivy --image bancolombia/devsecops-engine-tools:${{ github.event.inputs.version }})
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Publish a Docker image to Dockerhub
        run: |
          docker image push bancolombia/devsecops-engine-tools:${{ github.event.inputs.version }}
