name: Release

on:
  push:
    tags:
    - 'v[0-9].[0-9]+.[0-9]+' # Matches semantic versioning tags like v1.0.0, v2.1.3, etc.

jobs:

  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Generate a token of Github APP
        id: generate_token
        uses: actions/create-github-app-token@v2.2.0
        with:
          app-id: ${{ secrets.SEMREL_GITHUB_APP_ID }}
          private-key: ${{ secrets.SEMREL_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.release.tag_name }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Upgrade python.version
        run: sed -i "s/version = '.*'/version = '${{ env.RELEASE_VERSION }}'/" tools/devsecops_engine_tools/version.py

      - name: Save version
        uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa # v2.9
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          push-branch: "trunk"
          commit-message: 'docs: upgrade version to ${{ env.RELEASE_VERSION }} version [skip ci]'
          force-add: "true"
          force-push: "true"
          files: tools/devsecops_engine_tools/version.py
          name: Release Bot
          email: release-bot@bancolombia.com.co

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          sudo apt-get update

      - name: Build
        run: |
          cd tools/
          python -m virtualenv _venv
          source _venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install setuptools virtualenv wheel
          python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tools/dist/
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make git

      - name: Clone specific version of KICS
        run: |
          git clone https://github.com/Checkmarx/kics.git /tmp/kics
          cd /tmp/kics
          git checkout tags/$KICS_VERSION
        env:
          KICS_VERSION: ${{ vars.VAR_KICS_VERSION }}

      - name: Run go mod vendor
        working-directory: /tmp/kics
        run: go mod vendor
        
      - name: Build KICS binary
        working-directory: /tmp/kics
        run: |
          mkdir -p bin
          go build -o ./bin/kics cmd/console/main.go

      - name: Validate KICS
        run: |
          if [ ! -f /tmp/kics/bin/kics ]; then
            echo "Error: KICS binary was not generated"
            exit 1
          fi
          file /tmp/kics/bin/kics
          chmod +x /tmp/kics/bin/kics
          /tmp/kics/bin/kics version || echo "Error: KICS compiled, but does not run correctly"

      - name: Move KICS binary to custom folder
        run: |
          mkdir -p ./kics_binary/kics-devsecops
          cp /tmp/kics/bin/kics ./kics_binary/kics-devsecops/
          ls -la ./kics_binary
          ls -la ./kics_binary/kics-devsecops
          
      - name: Build and tag Docker image
        run: |
          sleep 180  # Wait 3 minutes
          docker build --build-arg VERSION=${{ env.RELEASE_VERSION }} -t bancolombia/devsecops-engine-tools:${{ env.RELEASE_VERSION }} -f docker/Dockerfile .
          docker tag bancolombia/devsecops-engine-tools:${{ env.RELEASE_VERSION }} bancolombia/devsecops-engine-tools:${{ env.RELEASE_VERSION }}

      - name: devsecops-engine-tools engine_container
        run: |
          set -e
          # Install devsecops-engine-tools
          pip3 install devsecops-engine-tools -q

          # Execute devsecops-engine-tools and handle the output
          output=$(devsecops-engine-tools --platform_devops github --remote_config_source local --remote_config_repo example_remote_config_local --module engine_container --tool trivy --image bancolombia/devsecops-engine-tools:${{ env.RELEASE_VERSION }})
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Publish a Docker image to Dockerhub
        run: |
          docker image push bancolombia/devsecops-engine-tools:${{ env.RELEASE_VERSION }}
