name: VSCode Build

on:
  push:
    branches:
      - trunk
      - feature/*
      - fix/*
    paths:
      - "ide_extension/vscode/devsecops/**"
      - ".github/workflows/vscode-build.yml"
      - ".github/workflows/vscode-release.yml"

  pull_request:
    branches:
      - trunk
    paths:
      - "ide_extension/vscode/devsecops/**"
      - ".github/workflows/vscode-build.yml"
      - ".github/workflows/vscode-release.yml"

jobs:
  # Prepare environment and build the plugin
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: ide_extension/vscode/devsecops/

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Compile extension
        run: npm run compile

  releaseDraft:
    name: Release draft
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/trunk'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: ide_extension/vscode/devsecops/

    steps:
      - name: Generate a token of Github APP
        id: generate_token
        uses: actions/create-github-app-token@v2.2.0
        with:
          app-id: ${{ secrets.SEMREL_GITHUB_APP_ID }}
          private-key: ${{ secrets.SEMREL_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '22'

      - name: Semantic Release
        run: npx -p semantic-release -p @semantic-release/git -p @semantic-release/changelog -p @semantic-release/exec semantic-release
        working-directory: ./ide_extension/vscode/devsecops/
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
